topics:
  bitcoin:
    - 'btc'
    - 'bitcoin'
    - 'BTC'
    - 'Bitcoin'
  ethereum:
    - 'eth'
    - 'ethereum'
    - 'ETH'
    - 'Ethereum'
  ripple:
    - 'xrp'
    - 'ripple'
    - 'XRP'
    - 'Ripple'
  litecoin:
    - 'ltc'
    - 'litecoin'
    - 'LTC'
    - 'Litecoin'

